# This is the default configuration file.

Jackpocket/SneakersJobControlSignal:
  Description: "A Sneakers `work` method, including `rescue` and `else` bodies, must return an `ack!`, `reject!`, or `requeue!` signal."
  Enabled: true

Jackpocket/SneakersNoInstanceVariable:
  Description: "A Sneakers class must not use instance variables."
  Enabled: true

Jackpocket/NoBugsnagNotify:
  Description: "Replace Bugsnag references with our ErrorReporter class."
  Enabled: true
  Exclude:
    - bin/bugsnag-console
    - config/initializers/bugsnag.rb
    - lib/error_reporter.rb
    - spec/lib/error_reporter_spec.rb
    - spec/controllers/application_controller_spec.rb
