name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Tests - Ruby ${{ matrix.ruby }}
    timeout-minutes: 5
    strategy:
      matrix:
        ruby:
          - '3.4'
          - '4.0'
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rspec
        env:
          RUBYOPT: "-W:deprecated --enable-frozen-string-literal --debug-frozen-string-literal"
